version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - node-network

  back-end:
    build:
      dockerfile: Dockerfile
      context: be
    container_name: back-end
    working_dir: /app
    networks:
      - node-network
    volumes:
      - ./be:/app
      - /app/node_modules
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGPASSWORD=postgres_password
    tty: true
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - db

  front-end:
    build:
      dockerfile: Dockerfile
      context: fe
    container_name: front-end
    working_dir: /app
    networks:
      - node-network
    volumes:
      - ./fe:/app
      - /app/node_modules
    tty: true
    ports:
      - "5173:5173"
    stdin_open: true
    #command: npm run dev

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    networks:
      - node-network
    depends_on:
      - back-end
      - front-end

networks:
  node-network:
    driver: bridge
